### ISSUE TITLE
Catalog of thing project setup

### ISSUE THREAD

**Issue by olaishola05** [netman5/catalog_of_my_things#29]
https://github.com/netman5/catalog_of_my_things/projects/2

- The team consists of 3 people
- @netman5 was assigned the tasks for team member 1, @AkshithaReddy1899 was assigned the tasks of team member 3, and @banlon-jones was assigned the tasks of team member 2

**Comment by dasileker** [comment]
### **Hi @netman5 @banlon-jones @AkshithaReddy1899,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
